### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by SimonBiggs** [moloney/dcm#1]
Hi @moloney,

I like what you've done here, making an asyncio wrapper around pynetdicom. Might you consider providing a license file for this software, eg Apache-2.0 as is used by PyMedPhys (https://github.com/pymedphys/pymedphys/blob/main/LICENSE)?

**Comment by moloney** [comment]
Added a LICENSE file.

**Comment by SimonBiggs** [comment]
Thanks @moloney :)
