### ISSUE TITLE
Output for additional elements like e.g. PatientBirthdate, PatientSex, AccessionNumber or StudyDescription

### ISSUE THREAD

**Issue by joshy** [moloney/dcm#6]
Hi, 

is there a way to query for additional elements? 

My dream would be that I can have a `--level series` query with the ability to output additional elements on the following levels:
* patient level
  - patient birth date
  - patient sex
* study level 
  - study description
  - accession number
 
 Or to have the possibility to query for additional fields per level query. Than I would query for all patients (+birth date, + sex), than the studies (+accession number) and than the series.

Thanks a lot for your time,
Joshy

**Comment by moloney** [comment]
There are a couple components to this.  You can query for whatever elements you like, but most DICOM network nodes will only support a very small number of elements being queried, the only way to find out is read their conformance statement or test it out.

The second part is the default output format for the query results is the `tree` format, which condenses each Patient/Study/Series/Instance to a single line and thus doesn't show all the available info.   You can specify `--out-format json` to the `query` CLI command to see all of the available info but in a less human readable format.  I guess supporting some sort of multi-line tree format that shows more of the queried info without resorting to full JSON might be good (probably in tandem to switching to using `rich` for producing the tree output).

**Comment by joshy** [comment]
> There are a couple components to this. You can query for whatever elements you like, but most DICOM network nodes will only support a very small number of elements being queried, the only way to find out is read their conformance statement or test it out.

Sure. What would be nice is if there is a CLI way to pass via parameter additional search tags, e.g. like DCMTK does it with passing `-k (0008,0050)`.  

> The second part is the default output format for the query results is the tree format, which condenses each Patient/Study/Series/Instance to a single line an ...

If the additional tags are only shown in the `json` output format maybe that is a solution that most of the users can live with.

Maybe a little bit of context what I want to use `dcm` for. I have build a search engine on [pacs and ris data](https://github.com/pacs-ris-crawler/pacs-ris-crawler) (metadata only). To query all the information I used `DCMTK` because `pydicom` and `pynetdicom` was too low level for me. Now I found about this tool and want to switch to it. But instead of using the CLI maybe I should just switch to using the python interface.

**Comment by moloney** [comment]
You can pass as many search terms as you like to the CLI `query` command. I don't have a fallback to use numeric tags currently, so you just need to use keywords instead. So you would do something like:

`$ dcm query mypacs PatientID='MyPatient' AccessionNumber=''`

Note that I did just recently add `AccessionNumber` to the list of elements we always query for (but again you won't see unless you use the `json` output from the CLI).

The python interface should be quite a bit more powerful and hopefully not much harder to use if you already know python. The QueryResult objects will be nicer to work with directly versus their JSON serialization.

**Comment by joshy** [comment]
> $ dcm query mypacs PatientID='MyPatient' AccessionNumber=''

Didn't know that this is possible. Thanks a lot.
